### ISSUE TITLE
[BUG] Self-installed fonts are not recognized correctly.

### ISSUE THREAD

**Issue by KasumiNova** [nmkj-io/rw-customfonts#1] opened 2022-09-10 06:58 UTC
As the title.
In Windows Environment.

**Comment by nmkj-io** [comment] 2022-09-18 04:34
Does that mean the list in the mod settings is empty? I heard that some fonts don't appear in the mod settings, and such fonts could be loaded by modifying the xml file of the mod, so you may try that.

Since the mod loads font names by just calling a single function `Font.GetOSInstalledFontNames()` [here](https://github.com/nmkj-io/rw-customfonts/blob/0fca532ded4b1273da93f9a17bb64716203fec9b/Source/CustomFonts/CustomFonts.cs#L119) which Unity provides, I'm right now not sure why some fonts are missing.

If you could tell which fonts are missing, then I'd try to reproduce the issue.

Thanks,

**Comment by KasumiNova** [comment] 2022-09-18 04:38
Thanks for replying to my question.
When I install my own ttf file for my system (e.g. JetBrains Mono, HarmoneyOS Sans SC, etc.), it doesn't show up correctly within the game, even though I restarted the system or the game.
It only shows the fonts that are already on the system by default, but not the custom fonts installed by the user.

**Comment by nmkj-io** [comment] 2022-09-18 05:27
Perhaps you installed your fonts under AppData directory, not system-wide. Fonts need to be placed at C:\Windows\Fonts and this would need the admin privilege. You can do this by
1. Select font files then right-click
2. Press "Install for all users" (this is under "show more options" menu if you're on Windows 11)
Then restart the game.

**Comment by KasumiNova** [comment] 2022-09-18 05:28
Thanks, I will find time to test it :)

**Comment by nmkj-io** [comment] 2022-09-26 10:29
I'm going to close the issue. Reopen this if the above doesn't work.

**Closed as completed by nmkj-io** 2022-09-26 10:29 UTC
